name: "Run IWPT bot"
on:
  push:
    branches:
      - 'syncom/test-crp-v5'
  schedule:
    # Daily at 09:42am, UTC
    - cron: '42 9 * * *'

jobs:
  run-iwpt-bot:
    strategy:
      fail-fast: false
      # Linux runner
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Set env"
        run: |
          set -euxo pipefail
          echo "TODAY_ISO8601=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: "Install deps"
        run: |
          set -euxo pipefail
          sudo apt update
          sudo apt install pari-gp

      - name: "Checkout code"
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: "Run bot"
        run: |
          set -euxo pipefail
          cd ${{ github.workspace }}/
          make install
          ./iwpt_bot_run.sh
        env:
          IWPT_APP_KEY: '${{ secrets.IWPT_APP_KEY }}'
          IWPT_APP_SECRET: '${{ secrets.IWPT_APP_SECRET }}'
          IWPT_OAUTH_TOKEN: '${{ secrets.IWPT_OAUTH_TOKEN }}'
          IWPT_OAUTH_TOKEN_SECRET: '${{ secrets.IWPT_OAUTH_TOKEN_SECRET }}'

      - name: "Create Pull Request"
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Add log for ${{ env.TODAY_ISO8601 }}"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: "log/${{ env.TODAY_ISO8601 }}.log"
          delete-branch: true
          title: "Add log for ${{ env.TODAY_ISO8601 }}"
          body: |
            Add today's IWPT log
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            iwpt log
            automated pr
          assignees: syncom
          reviewers: syncom
          draft: false
          base: ${{ github.head_ref }}